### ISSUE TITLE
Red base disappears

### ISSUE THREAD

**Issue by tkaden4** [Ukn0wnSoldure/ASG#6]
When at 500 x 500 resolution, the red base disappears before fully off the screen.

**Comment by aedans** [comment]
This is due to the fact that the entities outside the viewport are told not to render, and because of the red & blue base's large size, the viewport occasionally believes them to be off-screen when they are not. I'll be fixing this as soon as I add the Width and Height of the Model to the TexturedModel class, as the Width and Height are required to determine if the Model is on or off screen.

**Comment by aedans** [comment]
Fixed
